### PR TITLE
default to adding __init__.py files to directories

### PR DESCRIPTION
**Pull request by mattkatz**
Python unittest discover still relies on __init__.py files and doesn't
support namespace packages. By default we can create these but allow for
their suppression if using other test frameworks.

### CODE REVIEW

**Comment by mattkatz** [comment]
Ok this should solve your point. 

I am adding as a python specific concern, as I have a PR over on my fork that allows multilanguage support.

**Comment by mattkatz** [comment]
Rather, a PR is coming from my fork soon that allows multilanguage support

**Comment by ryneeverett** [comment]
Thanks! I took a brief look at your multilanguage branch and it looks like you're on the right track.

**Comment by ryneeverett** [comment]
By the way, I'd also be fine with making the default value `--package-python=False` when we add more language support.

**Pull request merged**
